cubefs/cubefs-csi

README.md

Initialize README.
Signed-off-by: Shuoran Liu <shuoranliu@gmail.com>

Initialize README.

---

README.md
deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml
go.mod
go.sum
pkg/chubaofs/cfs_server.go
pkg/chubaofs/driver.go
pkg/chubaofs/mountpoint_monitor.go
pkg/chubaofs/mountpoint_monitor_test.go
pkg/chubaofs/nodeserver.go
pkg/chubaofs/utils.go
pkg/csi-common/driver.go
pkg/csi-common/identityserver-default.go
pkg/csi-common/nodeserver-default.go

enhance: add invalid mount point monitor

---

README.md

Signed-off-by: Chengyu Liu <liuchengyu@jd.com>

enhance: udpate READEME

---

deploy/storageclass-share-volume.yaml
deploy/storageclass.yaml
pkg/chubaofs/cfs_server.go

Signed-off-by: Chengyu Liu <liuchengyu@jd.com>

enhance: support zone setting when the volume is created

---

deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml
pkg/chubaofs/cfs_server.go
pkg/chubaofs/mountpoint_monitor.go

support that masterAddr in StorageClass can set a string separated by comma composed by Master node ip

enhance: update masterAddr in StorageClass

---

README.md
pkg/chubaofs/controllerserver.go
pkg/chubaofs/mountpoint_monitor.go
pkg/chubaofs/nodeserver.go
pkg/chubaofs/utils.go
pkg/csi-common/driver_test.go
pkg/csi-common/utils_test.go

1. update README.yaml
2. add time statictics when mount

Enhancement: update README.yaml

---

pkg/chubaofs/mountpoint_monitor.go

fix: update mountpoint monitor

---

deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml

upgrade cfs-client version to 2.1.0

---

build/build_cfs_client.sh
deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml
pkg/chubaofs/cfs_server.go
pkg/chubaofs/controllerserver.go
pkg/csi-common/utils.go

New features:
1. Using different user's name when create a new volume, it aviod that all S3 user use same AK and SK
2. Upgrade cfs-client version to 2.2.1
Refactor
1. Always compile the lastest version of ChubaoFS client
2. Update image version of ChubaoFS CSI

Feature: Using different user's name when create a new volume, it aviod that all S3 user use same AK and SK

---

deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml

upgrade cfs-client to 2.2.2 version

---

deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml
examples/deployment-static.yaml
examples/deployment.yaml

Upgrade ChubaoFS version 2.4.0

---

deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml
pkg/chubaofs/cfs_server.go

Fix issues #47, and retry other master server when the first server was no response or crash
Reported-by: zcola <zhangrui90@163.com>

Fix issues #47

---

pkg/chubaofs/nodeserver.go

[VolumeMount subPath feature ref](https://github.com/kubernetes/kubernetes/blob/v1.22.0/staging/src/k8s.io/api/core/v1/types.go#L1882)
[Kubelet implemt logic ref](https://github.com/kubernetes/kubernetes/blob/v1.22.0/pkg/volume/util/subpath/subpath_linux.go#L158)

Support remount damaged volumes using sub path mount feature

---

BUILD.md
Makefile
README.md
build/build_cfs_client.sh
build/build_docker.sh
cmd/cubefs.go
deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml
deploy/csi-rbac.yaml
deploy/storageclass-default.yaml
deploy/storageclass.yaml
docs/volume-expansion.md
examples/deployment-static.yaml
examples/deployment.yaml
examples/pv-static.yaml
go.mod
pkg/cubefs/cfs_server.go
pkg/cubefs/controllerserver.go
pkg/cubefs/driver.go
pkg/cubefs/identityserver.go
pkg/cubefs/nodeserver.go
pkg/cubefs/utils.go

https://github.com/cubeFS/cubefs-csi/issues/61

Rename project name from ChubaoFS to CubeFS

---

pkg/cubefs/nodeserver.go

the problem describe as [here](https://github.com/cubefs/cubefs-csi/issues/79)

fix: csi need to remove target path before return when error occurs

---

build/Dockerfile
build/build_cfs_client.sh
build/build_docker.sh

detail content see the https://github.com/cubefs/cubefs-csi/issues/94

fix(build): fix the build script of cubefs client

---

pkg/cubefs/cfs_server.go

the problem detail is here https://github.com/cubefs/cubefs-csi/issues/92

fix(csi): fix duplicate vol problem

---

CODE_OF_CONDUCT.md

feat(doc): Add the code of conduct rules

---

README.md

feat(doc): Add governace rules

---

deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml

update image version from v3.2.0 to v3.3.2, every version make a commit.

update image version

---

Makefile
build/build_cfs_client.sh
deploy/csi-controller-deployment.yaml
deploy/csi-node-daemonset.yaml

update image version to 3.5.1
